spring.application.name=backend


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tradelens?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.org.springframework.jdbc.support.JdbcTransactionManager=debug

jwt.secret=${JWT_SECRET}
jwt.expiration=86400


# 文件上传限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 存储策略配置 (local 或 oss)
storage.type=local

# 本地存储路径
file.upload-dir=D:/zz-Final/tradeLens/data/

# 静态资源映射 (Spring Boot 默认配置，确保 WebMvcConfig 中也有相应配置)
spring.web.resources.static-locations=file:${file.upload-dir}

# 支付宝相关的配置
alipay.appId=${APPID}
alipay.merchantPrivateKey=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCD6Cx2TXRur22pqj7BYG1ZScs1S1youD97DvMZ1b/bgXOJsComlnEC2BeUYWytuDLncJoOOmAYpp1vGtKxiKY2eCT06LzSrWUG9AoT90ys4iBPEXl9r3dzjIC/rGcqB0AJkTpjnbjOoRdyJ3vBzOjibrUItnxNRitMwSeyS+D+SCXUKtBhl4F4+jlh71sjBwAempRiEP3i9um1cnuTRH/EmhUI+CwGJ0/BpA8XFLxIA1vLJFz7EmuK9RO2W30Xbd5B9xKss1to/XS2zLvwU+CFrt1xPU8oE5ELLouv8xUF63ki1O8U6ZP9Hmnlb8K2aj6eis9WhYtS6C1I30aViJuTAgMBAAECggEATxJAhPJNV4SF4m0RjW42Xo3j6KCyfNlmBGijxdriVb01+1XFDrikKiZLjEESmtiOezp+vwSzUlOekFmt74qQyJog3Uce2dPjedWUrP9T0VcEMyGwiG1E19lj3IKGnSUXeCS8sbZ8cDEVEvMkNrqU6BehIgXyYYgssKghGbputz7AK2RAAXsdaHf7oZdtCeHWC4jF7xiEkSbbIjaLMKuK4bVnC0I7U784NCnc7kTl8tjnF4f6sygabVywMA90hkdYyVcyS55ewgK3NF04Y4cYirWnu8Ve2D5nUE7XQ6Dl3XiMrYrKCAPVmUHjFU1OamUbs00xKOHGrRie/nP96LdT0QKBgQC+U/VQvWnUGeGym3KVMzsnQcxAFxrGXwlk/GYw5bZ34A8Z/7cmUFdKkWWe1ut6/rmXGWY756VOU0nxhaEL1E4bvmTO3sRGZmHUymrIvwmnxu1doVr3F4gfOnz+Hch1cugbtCDZkge7w7yzN68JkWXG1Vsu+e0MSFGbz6u/uwmsZwKBgQCxa8VlVIdZVvr+bkM64g3e8+7+FTMA1SNNYRsdG6L9f2G6OHaBIR6lfm0dPrPeYh9wUXayInyZgAgLzvW2BivY35uf6ex1xmaMQ1wRPayeGeehPpbUM/WSe77wuF00zvyS8Z6l662wx8Dm1u7zqb6wybbtnmDZjBxtA6CiNFJb9QKBgEkwnBuKW1H3CfXXFT8OzmaQRO04dVFnZoNxFBMlov+CKAyFa3bOWmMQepWUbEWGAvR6DfhnYgg2uy6nhoC4CbldhAKRY8T2xhRAKsQ7wojEVK82x3ZRlET+BubpqRaRM3TD1gYUw+iOotgAR81UHmFR1pi//0pD3S4ftBos4NFtAoGAOIM2dgdNsXRWMHLYsUnN10Vly8Le4xYAz6XtqADkktBfRZy0in8NLvOtN9KAIoaosvMP1r/LZm10oqZCd79RehwHixFMw1r10RmnmspFUHq54A96pY8DWqxV7oEbFzYTF48k1H7UbWnDFQRDSpO37MHjpZ58BO9vIn40TVZTIX0CgYA/HOO37PsjNqxonaidy3N+ed0qV0X74PCrEFumYFJq8J4A/iDEkb+8FJ3fx/aO2ITsBssoVCRY61pg6Q1mIptKEglbiIOOnlPffAsXehtLUWCQ06vL0IogIgFjkYFdi/aiRcrQQqUtTtBDg0oX16szE/O6QlRdNp7Rkyt+ffWsvQ==
alipay.alipayPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsO3qe2I8JdxUZBWgubrTvfKpSOGD3EznU/AMjDpy8H9ygoe2gslQBEKU9ZXyz1y/MF5NdJGZTYN+al78kLImDeGHLloEITvoDb9s4we5Gmu+GwuS/GG4paTi1O+SqirxodwSSNawKNNiDpuMFCX7VVavMvn4tJxDN1fsR0Xg5X8EUPc+07YgDu6n8Q1tU8SuxCOsSepYsOMqq+i6y7tciqKKLnLFz6FzwmXdjfwbjVnPzY1hraoT5qTwhqMoTViqF6HrhhBCv3G0Aop5CbXFnUAcJVOufig5EgUVS5Gtm+Qi5hjYamhgFcXlvNHskdjog2GhMvThpDMzKDcfTE96DwIDAQAB
alipay.notifyUrl=http://b93d3b67.natappfree.cc/api/alipay/notify

#alipay.returnUrl=http://zbe265aa.natappfree.cc/memberOrder.html
alipay.returnUrl=http://localhost:5173/
alipay.signType=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 阿里云通义千问大模型 API-KEY
alibaba.dashscope.api-key=${API_KEY}
